// SquirrelDB Go SDK - Types
// Generated by sdk-generator v0.1.0
// DO NOT EDIT MANUALLY

package squirreldb

// Document - A document stored in SquirrelDB
type Document struct {
	Id string `json:"id"`
	Collection string `json:"collection"`
	Data map[string]interface{} `json:"data"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ChangeEvent - A change event from a subscription
type ChangeEvent struct {
	Type ChangeType `json:"type"`
	Document *Document `json:"document"`
	Old *interface{} `json:"old"`
	New *Document `json:"new"`
}

// Bucket - Storage bucket
type Bucket struct {
	Name string `json:"name"`
	CreatedAt string `json:"created_at"`
}

// StorageObject - Object in storage
type StorageObject struct {
	Key string `json:"key"`
	Size int64 `json:"size"`
	Etag string `json:"etag"`
	LastModified string `json:"last_modified"`
	ContentType *string `json:"content_type"`
}


// ChangeType represents the type of change
type ChangeType string

const (
	ChangeTypeInitial ChangeType = "initial"
	ChangeTypeInsert ChangeType = "insert"
	ChangeTypeUpdate ChangeType = "update"
	ChangeTypeDelete ChangeType = "delete"
)
